sudo: required
services:
  - docker

before_install:
  - docker build -t brian/react-test -f ./client/Dockerfile.dev ./client

# Place to add automated testing here
script:
  - docker run -e CI=true brian/react-test npm test

after_success:
  - docker build -t brian/multi-client ./client
  - docker build -t brian/multi-nginx ./nginx
  - docker build -t brian/multi-server ./server
  - docker build -t brian/multi-worker ./worker
  # Login into Docker CLI
  # DOCKER_PASSWORD and DOCKER_ID are travis CI environment variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to dockerhub
  - docker push brian/multi-client
  - docker push brian/multi-nginx
  - docker push brian/multi-server
  - docker push brian/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  # The S3 bucket name
  bucket_name: "elasticbeanstalk-us-east-1-162035663238"
  # Not sure where this is from. May just leave it
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
